### ISSUE TITLE
Too many cleanup activities

### ISSUE THREAD

**Issue by nwcell** [adobe/parliament-client-template#23]
### Expected Behaviour
When I add/remove .md files, it should update my build seemlessly.
### Actual Behaviour
Currently, when I make a significant update to the .md filed I have to bounce the dev server, run `gatsby clean`, AND delete the content folder.
### Reproduce Scenario (including but not limited to)
Add a .md file, while in dev mode.  The file isn't available until I run `gatsby clean` & then `rm -rf ./src/content`
#### Steps to Reproduce
Add a .md file, while in dev mode.
#### Platform and Version
node v12.18.3 on osx
#### Sample Code that illustrates the problem
```
cd {source repo}
touch new.md
# add new.md to the manifest.json
```

**Comment by macdonst** [comment]
@nwcell with our latest commits we have fixed things so adding/removing files should automatically update your build without having to stop the develop process and run clean/rm.
